name: Deploy SSL Certificate

on:
  push:
    branches:
      - main
  workflow_dispatch: # to manually run workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode and Set SSL Certificate
        run: echo "SSL_CERTIFICATE=${{ secrets.SSL_CERTIFICATE }}" >> $GITHUB_ENV

      #- uses: akiojin/decode-base64-github-action@v0.1.0
       # with:
        #  base64: ${{ secrets.SSL_CERTIFICATE }}
         # environment: DECODED
      #- run: |
       #   echo $DECODED

      #- name: Echo value
      # run: echo "$SSL_CERTIFICATE"

      - name: Build Docker Image
        run: |
          docker build --build-arg SSL_CERTIFICATE="$SSL_CERTIFICATE" -t my-image:latest .
